---
- name: install rocksdbjni dependencies
  apt: pkg={{ item }}
  with_items:
    - openjdk-7-jdk
    - maven
    - autoconf
    - libtool

- name: make rocksdbjni dir
  sudo_user: "{{ rocksdb_user }}"
  file: >
    state=directory
    path={{ rocksdbjni_path }}

- name: clone rocksdbjni repo
  sudo_user: "{{ rocksdb_user }}"
  git: >
    repo=https://github.com/fusesource/rocksdbjni.git
    dest={{ rocksdbjni_path }}
    version={{ rocksdbjni_version }}

- name: build rocksdbjni
  sudo_user: "{{ rocksdb_user }}"
  command: >
    chdir={{ rocksdbjni_path }}
    mvn clean install

- name: build rocksdbjni-linux64
  sudo_user: "{{ rocksdb_user }}"
  environment:
    ROCKSDB_HOME: "{{ rocksdb_path }}"
    SNAPPY_HOME: "/usr/include/"
    JAVA_HOME: "/usr/lib/jvm/java-7-openjdk-amd64/"
  command: >
    chdir={{ rocksdbjni_path }}/rocksdbjni-linux64
    mvn clean install {{ '-DskipTests=true' if not rocksdb_tests else '' }}
